services:
  backend:
    image: zenmind-app-server-backend
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./data
        target: /data
      # BEGIN GENERATED CONFIG FILES VOLUMES
      - type: bind
        source: ./release/config-files.runtime.yml
        target: /app/config/config-files.runtime.yml
      - type: bind
        source: ./.env
        target: /app/config/zenmind-root.env
      - type: bind
        source: ../mcp-server-mock/.env
        target: /app/config/mcp-server-mock.env
      - type: bind
        source: ../term-webclient/release/.env
        target: /app/config/term-webclient-release.env
      - type: bind
        source: ../term-webclient/release/application.yml
        target: /app/config/term-webclient-release.application.yml
      # END GENERATED CONFIG FILES VOLUMES
    ports:
      - "${BACKEND_PORT}:8080"
    networks:
      zenmind-network:
        aliases:
          - app-server-backend

  frontend:
    image: zenmind-app-server-frontend
    build:
      context: ./frontend
      args:
        VITE_BASE_PATH: ${VITE_BASE_PATH:-/admin/}
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      zenmind-network:
        aliases:
          - app-server-frontend

networks:
  zenmind-network:
    external: true
