PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS APP_USER_ (
    USER_ID_ TEXT PRIMARY KEY,
    USERNAME_ TEXT NOT NULL UNIQUE,
    PASSWORD_BCRYPT_ TEXT NOT NULL,
    DISPLAY_NAME_ TEXT NOT NULL,
    STATUS_ TEXT NOT NULL,
    CREATE_AT_ TIMESTAMP NOT NULL,
    UPDATE_AT_ TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_APP_USER_USERNAME_ ON APP_USER_(USERNAME_);

CREATE TABLE IF NOT EXISTS OAUTH2_CLIENT_ (
    ID_ TEXT PRIMARY KEY,
    CLIENT_ID_ TEXT NOT NULL UNIQUE,
    CLIENT_ID_ISSUED_AT_ TIMESTAMP NOT NULL,
    CLIENT_SECRET_ TEXT,
    CLIENT_SECRET_EXPIRES_AT_ TIMESTAMP,
    CLIENT_NAME_ TEXT NOT NULL,
    CLIENT_AUTH_METHODS_ TEXT NOT NULL,
    AUTH_GRANT_TYPES_ TEXT NOT NULL,
    REDIRECT_URIS_ TEXT,
    POST_LOGOUT_REDIRECT_URIS_ TEXT,
    SCOPES_ TEXT NOT NULL,
    CLIENT_SETTINGS_ TEXT NOT NULL,
    TOKEN_SETTINGS_ TEXT NOT NULL,
    REQUIRE_PKCE_ INTEGER NOT NULL DEFAULT 1,
    STATUS_ TEXT NOT NULL DEFAULT 'ACTIVE',
    CREATE_AT_ TIMESTAMP NOT NULL,
    UPDATE_AT_ TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_OAUTH2_CLIENT_CLIENT_ID_ ON OAUTH2_CLIENT_(CLIENT_ID_);
CREATE INDEX IF NOT EXISTS IDX_OAUTH2_CLIENT_STATUS_ ON OAUTH2_CLIENT_(STATUS_);

CREATE TABLE IF NOT EXISTS JWK_KEY_ (
    KEY_ID_ TEXT PRIMARY KEY,
    PUBLIC_KEY_ TEXT NOT NULL,
    PRIVATE_KEY_ TEXT NOT NULL,
    CREATE_AT_ TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS DEVICE_ (
    DEVICE_ID_ TEXT PRIMARY KEY,
    DEVICE_NAME_ TEXT NOT NULL,
    DEVICE_TOKEN_BCRYPT_ TEXT NOT NULL,
    STATUS_ TEXT NOT NULL DEFAULT 'ACTIVE',
    LAST_SEEN_AT_ TIMESTAMP,
    REVOKED_AT_ TIMESTAMP,
    CREATE_AT_ TIMESTAMP NOT NULL,
    UPDATE_AT_ TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_DEVICE_STATUS_ ON DEVICE_(STATUS_);
CREATE INDEX IF NOT EXISTS IDX_DEVICE_UPDATE_AT_ ON DEVICE_(UPDATE_AT_ DESC);

CREATE TABLE IF NOT EXISTS INBOX_MESSAGE_ (
    MESSAGE_ID_ TEXT PRIMARY KEY,
    TITLE_ TEXT NOT NULL,
    CONTENT_ TEXT NOT NULL,
    TYPE_ TEXT NOT NULL,
    PAYLOAD_JSON_ TEXT,
    SENDER_ TEXT NOT NULL,
    READ_AT_ TIMESTAMP,
    CREATE_AT_ TIMESTAMP NOT NULL,
    UPDATE_AT_ TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_INBOX_CREATE_AT_ ON INBOX_MESSAGE_(CREATE_AT_ DESC);
CREATE INDEX IF NOT EXISTS IDX_INBOX_READ_AT_ ON INBOX_MESSAGE_(READ_AT_);

CREATE TABLE IF NOT EXISTS CHAT_EVENT_DEDUP_ (
    CHAT_ID_ TEXT NOT NULL,
    RUN_ID_ TEXT NOT NULL,
    CREATE_AT_ TIMESTAMP NOT NULL,
    PRIMARY KEY (CHAT_ID_, RUN_ID_)
);

CREATE TABLE IF NOT EXISTS TOKEN_AUDIT_ (
    TOKEN_ID_ TEXT PRIMARY KEY,
    SOURCE_ TEXT NOT NULL,
    TOKEN_VALUE_ TEXT NOT NULL,
    TOKEN_SHA256_ TEXT NOT NULL UNIQUE,
    USERNAME_ TEXT,
    DEVICE_ID_ TEXT,
    DEVICE_NAME_ TEXT,
    CLIENT_ID_ TEXT,
    AUTHORIZATION_ID_ TEXT,
    ISSUED_AT_ TIMESTAMP NOT NULL,
    EXPIRES_AT_ TIMESTAMP,
    REVOKED_AT_ TIMESTAMP,
    CREATE_AT_ TIMESTAMP NOT NULL,
    UPDATE_AT_ TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_TOKEN_AUDIT_SOURCE_ ON TOKEN_AUDIT_(SOURCE_);
CREATE INDEX IF NOT EXISTS IDX_TOKEN_AUDIT_ISSUED_AT_ ON TOKEN_AUDIT_(ISSUED_AT_ DESC);
CREATE INDEX IF NOT EXISTS IDX_TOKEN_AUDIT_EXPIRES_AT_ ON TOKEN_AUDIT_(EXPIRES_AT_);
CREATE INDEX IF NOT EXISTS IDX_TOKEN_AUDIT_DEVICE_ID_ ON TOKEN_AUDIT_(DEVICE_ID_);
CREATE INDEX IF NOT EXISTS IDX_TOKEN_AUDIT_AUTHORIZATION_ID_ ON TOKEN_AUDIT_(AUTHORIZATION_ID_);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_TOKEN_AUDIT_SHA256_ ON TOKEN_AUDIT_(TOKEN_SHA256_);

CREATE TABLE IF NOT EXISTS oauth2_authorization (
    id TEXT PRIMARY KEY,
    registered_client_id TEXT NOT NULL,
    principal_name TEXT NOT NULL,
    authorization_grant_type TEXT NOT NULL,
    authorized_scopes TEXT,
    attributes BLOB,
    state TEXT,

    authorization_code_value BLOB,
    authorization_code_issued_at TIMESTAMP,
    authorization_code_expires_at TIMESTAMP,
    authorization_code_metadata BLOB,

    access_token_value BLOB,
    access_token_issued_at TIMESTAMP,
    access_token_expires_at TIMESTAMP,
    access_token_metadata BLOB,
    access_token_type TEXT,
    access_token_scopes TEXT,

    oidc_id_token_value BLOB,
    oidc_id_token_issued_at TIMESTAMP,
    oidc_id_token_expires_at TIMESTAMP,
    oidc_id_token_metadata BLOB,

    refresh_token_value BLOB,
    refresh_token_issued_at TIMESTAMP,
    refresh_token_expires_at TIMESTAMP,
    refresh_token_metadata BLOB,

    user_code_value BLOB,
    user_code_issued_at TIMESTAMP,
    user_code_expires_at TIMESTAMP,
    user_code_metadata BLOB,

    device_code_value BLOB,
    device_code_issued_at TIMESTAMP,
    device_code_expires_at TIMESTAMP,
    device_code_metadata BLOB
);

CREATE INDEX IF NOT EXISTS IDX_OAUTH2_AUTH_PRINCIPAL ON oauth2_authorization(principal_name);
CREATE INDEX IF NOT EXISTS IDX_OAUTH2_AUTH_STATE ON oauth2_authorization(state);

CREATE TABLE IF NOT EXISTS oauth2_authorization_consent (
    registered_client_id TEXT NOT NULL,
    principal_name TEXT NOT NULL,
    authorities TEXT NOT NULL,
    PRIMARY KEY (registered_client_id, principal_name)
);

DROP VIEW IF EXISTS OAUTH2_AUTHORIZATION_;
CREATE VIEW OAUTH2_AUTHORIZATION_ AS
SELECT
    id AS AUTHORIZATION_ID_,
    registered_client_id AS REGISTERED_CLIENT_ID_,
    principal_name AS PRINCIPAL_NAME_,
    authorization_grant_type AS AUTHORIZATION_GRANT_TYPE_,
    authorized_scopes AS AUTHORIZED_SCOPES_,
    state AS STATE_,
    access_token_issued_at AS ACCESS_TOKEN_ISSUED_AT_,
    access_token_expires_at AS ACCESS_TOKEN_EXPIRES_AT_,
    refresh_token_issued_at AS REFRESH_TOKEN_ISSUED_AT_,
    refresh_token_expires_at AS REFRESH_TOKEN_EXPIRES_AT_
FROM oauth2_authorization;

DROP VIEW IF EXISTS OAUTH2_CONSENT_;
CREATE VIEW OAUTH2_CONSENT_ AS
SELECT
    registered_client_id AS REGISTERED_CLIENT_ID_,
    principal_name AS PRINCIPAL_NAME_,
    authorities AS AUTHORITIES_
FROM oauth2_authorization_consent;
